# Generated by Django 4.0.2 on 2022-08-01 00:20

from django.db import migrations, models
import poliwag.common.nanoid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthPhoneChallenge',
            fields=[
                ('id', models.CharField(default=poliwag.common.nanoid.NanoId.gen, max_length=13, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.IntegerField()),
                ('num_attempts', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField()),
            ],
        ),
    ]
