# Generated by Django 4.0.2 on 2022-08-01 00:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authphonechallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_phone_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='authphonechallenge',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('user',), name='active_pchal_per_user'),
        ),
    ]
