# Generated by Django 4.0.2 on 2022-08-19 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import poliwag.common.nanoid
import poliwag.core.user.constants


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(default=poliwag.common.nanoid.NanoId.gen, max_length=13, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarding_status', models.CharField(blank=True, choices=[('ACCOUNT_DETAILS', 'ACCOUNT_DETAILS'), ('ABOUT_YOU', 'ABOUT_YOU'), ('SUITABILITY', 'SUITABILITY'), ('COMPLIANCE', 'COMPLIANCE'), ('OPEN_YOUR_ACCOUNT', 'OPEN_YOUR_ACCOUNT'), ('TRANSFER_SHARES', 'TRANSFER_SHARES')], default=poliwag.core.user.constants.OnboardingStatusEnum['ACCOUNT_DETAILS'], max_length=50, null=True)),
                ('persona_inquiry_id', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('legal_first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('legal_last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('street_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('citizenship_country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('ssn', models.CharField(blank=True, max_length=9, null=True)),
                ('employment_status', models.CharField(blank=True, choices=[('FULL_TIME', 'FULL_TIME'), ('PART_TIME', 'PART_TIME'), ('SELF_EMPLOYED', 'SELF_EMPLOYED'), ('RETIRED', 'RETIRED'), ('NOT_EMPLOYED', 'NOT_EMPLOYED')], max_length=50, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('gross_income_current_year', models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True)),
                ('gross_income_previous_year', models.DecimalField(blank=True, decimal_places=6, max_digits=25, null=True)),
                ('estimated_net_worth', models.CharField(blank=True, choices=[('UNDER_ONE_MILLION', 'UNDER_ONE_MILLION'), ('ONE_TO_TWO_MILLION', 'ONE_TO_TWO_MILLION'), ('TWO_TO_FIVE_MILLION', 'TWO_TO_FIVE_MILLION'), ('FIVE_TO_TEN_MILLION', 'FIVE_TO_TEN_MILLION'), ('OVER_TEN_MILLION', 'OVER_TEN_MILLION')], max_length=50, null=True)),
                ('is_associated_with_securities_industry', models.BooleanField(blank=True, null=True)),
                ('is_public_company_controller', models.BooleanField(blank=True, null=True)),
                ('is_senior_government_official', models.BooleanField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.CharField(default=poliwag.common.nanoid.NanoId.gen, max_length=13, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('CUSTOMER_ID_FORM', 'CUSTOMER_ID_FORM')], max_length=20)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to='documents.document')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
